dist: bionic
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm install
script:
  - npm test
jobs:
  include:
    - stage: npm release
      node_js: "10"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
