version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

executors:
  docker-node:
    parameters:
      version:
        default: "lts"
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>

commands:
  install:
    steps:
      - run:
          name: Install
          command: npm install
  test:
    steps:
      - run:
          name: Test
          command: npm test
  release:
    steps:
      - run:
          name: Release
          command: npx semantic-release

jobs:
  test_and_scan:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - prodsec/security_scans:
          mode: auto
      - test

  release_package:
    resource_class: small
    executor:
      name: docker-node
    steps:
      - checkout
      - install
      - release

workflows:
  ci_cd:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: cli-alerts

      - test_and_scan:
          name: Test and scan
          context: 
            - nodejs-install
            - devex_cli

      - release_package:
          name: Release
          context: nodejs-lib-release
          requires:
            - test_and_scan
          filters:
            branches:
              only:
                - master
